
import { Sparkles, Users, Cpu, Database, Cloud, Layers, LucideIcon } from 'lucide-react';

export interface ServiceData {
    title: string;
    icon: LucideIcon;
    description: string;
    content: string;
    image: string;
}

export const SERVICES_DATA: Record<string, ServiceData> = {
    'scaling-ai': {
        title: "Scaling AI",
        icon: Sparkles,
        description: `Move beyond experimental pilots to enterprise-grade AI ecosystems. We specialize in operationalizing machine learning (MLOps) to ensure your models are scalable, ethical, and integrated into your core business logic for maximum ROI.`,
        content: `Scaling AI is a multi-faceted challenge that extends far beyond selecting a high-performing model. It requires a fundamental shift in platform engineering, data governance, and organizational culture. Our approach focuses on building 'Production-First' AI. This means establishing robust data pipelines that handle real-time ingestion, implementing automated model monitoring to detect drift, and ensuring that your AI infrastructure can scale elastically with demand. We help you navigate the complexities of LLM orchestration, vector databases, and retrieval-augmented generation (RAG) to turn raw data into a strategic competitive advantage. By bridging the gap between data science and software engineering, we ensure your AI initiatives deliver measurable, long-term impact rather than just technical proof-of-concepts.

            Scaling AI is a multi-faceted challenge that extends far beyond selecting a high-performing model. It requires a fundamental shift in platform engineering, data governance, and organizational culture. Our approach focuses on building 'Production-First' AI. This means establishing robust data pipelines that handle real-time ingestion, implementing automated model monitoring to detect drift, and ensuring that your AI infrastructure can scale elastically with demand. We help you navigate the complexities of LLM orchestration, vector databases, and retrieval-augmented generation (RAG) to turn raw data into a strategic competitive advantage. By bridging the gap between data science and software engineering, we ensure your AI initiatives deliver measurable, long-term impact rather than just technical proof-of-concepts.

            Scaling AI is a multi-faceted challenge that extends far beyond selecting a high-performing model. It requires a fundamental shift in platform engineering, data governance, and organizational culture. Our approach focuses on building 'Production-First' AI. This means establishing robust data pipelines that handle real-time ingestion, implementing automated model monitoring to detect drift, and ensuring that your AI infrastructure can scale elastically with demand. We help you navigate the complexities of LLM orchestration, vector databases, and retrieval-augmented generation (RAG) to turn raw data into a strategic competitive advantage. By bridging the gap between data science and software engineering, we ensure your AI initiatives deliver measurable, long-term impact rather than just technical proof-of-concepts.`,
        image: "/images/generative-ai.webp"
    },
    'customer-experience': {
        title: "Customer Experience",
        icon: Users,
        description: `Design and deploy frictionless digital journeys that bridge the gap between user needs and business goals. We leverage behavioral data and emotive design to create experiences that drive industry-leading retention.`,
        content: `In an era where switching costs are near zero, the quality of your customer experience (CX) is your most significant differentiator. We don't just build interfaces; we architect end-to-end journeys that delight users at every touchpoint. Our methodology blends deep design thinking with rigorous technical execution. We begin by uncovering the 'unmet needs' of your audience through comprehensive user research and journey mapping. From there, we build high-performance web and mobile applications characterized by intuitive navigation, accessibility, and lightning-fast response times. By integrating advanced personalization engines and real-time feedback loops, we ensure that your digital products evolve alongside your customers' expectations. The result is a seamless harmony between aesthetic beauty and functional excellence that transforms casual users into brand advocates.

                In an era where switching costs are near zero, the quality of your customer experience (CX) is your most significant differentiator. We don't just build interfaces; we architect end-to-end journeys that delight users at every touchpoint. Our methodology blends deep design thinking with rigorous technical execution. We begin by uncovering the 'unmet needs' of your audience through comprehensive user research and journey mapping. From there, we build high-performance web and mobile applications characterized by intuitive navigation, accessibility, and lightning-fast response times. By integrating advanced personalization engines and real-time feedback loops, we ensure that your digital products evolve alongside your customers' expectations. The result is a seamless harmony between aesthetic beauty and functional excellence that transforms casual users into brand advocates.

                In an era where switching costs are near zero, the quality of your customer experience (CX) is your most significant differentiator. We don't just build interfaces; we architect end-to-end journeys that delight users at every touchpoint. Our methodology blends deep design thinking with rigorous technical execution. We begin by uncovering the 'unmet needs' of your audience through comprehensive user research and journey mapping. From there, we build high-performance web and mobile applications characterized by intuitive navigation, accessibility, and lightning-fast response times. By integrating advanced personalization engines and real-time feedback loops, we ensure that your digital products evolve alongside your customers' expectations. The result is a seamless harmony between aesthetic beauty and functional excellence that transforms casual users into brand advocates.`,
        image: "/images/customer-experience.webp"
    },
    'product-innovation': {
        title: "Product Innovation",
        icon: Cpu,
        description: `Accelerate your time-to-market with a lean approach to product development. We help you identify high-growth opportunities, validate them through rapid prototyping, and build scalable MVPs that define new categories.`,
        content: `True innovation is the intersection of technical feasibility, business viability, and human desirability. We help organizations break out of 'legacy thinking' by implementing modern product management practices. Our innovation labs work as an extension of your team to rapidly prototype ideas, testing them against real-world scenarios before a single line of production code is written. We utilize a 'Lean Engineering' mindset—focusing on the core value proposition to reduce waste and accelerate feedback loops. Whether you are launching a brand-new digital venture or reinventing a flagship product, we provide the technical discipline and creative spark needed to succeed. Our process includes competitive landscape analysis, feature prioritization frameworks, and iterative development cycles that ensure your product remains agile enough to pivot based on market response.

                True innovation is the intersection of technical feasibility, business viability, and human desirability. We help organizations break out of 'legacy thinking' by implementing modern product management practices. Our innovation labs work as an extension of your team to rapidly prototype ideas, testing them against real-world scenarios before a single line of production code is written. We utilize a 'Lean Engineering' mindset—focusing on the core value proposition to reduce waste and accelerate feedback loops. Whether you are launching a brand-new digital venture or reinventing a flagship product, we provide the technical discipline and creative spark needed to succeed. Our process includes competitive landscape analysis, feature prioritization frameworks, and iterative development cycles that ensure your product remains agile enough to pivot based on market response.

                True innovation is the intersection of technical feasibility, business viability, and human desirability. We help organizations break out of 'legacy thinking' by implementing modern product management practices. Our innovation labs work as an extension of your team to rapidly prototype ideas, testing them against real-world scenarios before a single line of production code is written. We utilize a 'Lean Engineering' mindset—focusing on the core value proposition to reduce waste and accelerate feedback loops. Whether you are launching a brand-new digital venture or reinventing a flagship product, we provide the technical discipline and creative spark needed to succeed. Our process includes competitive landscape analysis, feature prioritization frameworks, and iterative development cycles that ensure your product remains agile enough to pivot based on market response.`,
        image: "/images/product-innovation.webp"
    },
    'data-modernization': {
        title: "Data Modernization",
        icon: Database,
        description: `Break down data silos and build a unified, secure data architecture. We transform your raw data into a clean, accessible, and high-velocity asset ready for advanced analytics and automated decision-making.`,
        content: `Data is often cited as the new oil, but without a modern refinery, it remains a liability rather than an asset. Our data modernization services focus on migrating legacy on-premise warehouses to high-performance cloud data platforms like Snowflake, BigQuery, or Databricks. We implement modern data stack (MDS) principles, including automated ELT pipelines, data modeling with dbt, and rigorous data quality monitoring. Beyond the architecture, we prioritize 'Data Democratization'—ensuring that business stakeholders have self-service access to reliable insights through governed BI layers. We also tackle the critical challenges of data privacy and compliance (GDPR/CCPA) by embedding security into the data lifecycle. By establishing a 'Single Source of Truth,' we empower your organization to move from reactive reporting to predictive modeling and real-time operational intelligence.

                Data is often cited as the new oil, but without a modern refinery, it remains a liability rather than an asset. Our data modernization services focus on migrating legacy on-premise warehouses to high-performance cloud data platforms like Snowflake, BigQuery, or Databricks. We implement modern data stack (MDS) principles, including automated ELT pipelines, data modeling with dbt, and rigorous data quality monitoring. Beyond the architecture, we prioritize 'Data Democratization'—ensuring that business stakeholders have self-service access to reliable insights through governed BI layers. We also tackle the critical challenges of data privacy and compliance (GDPR/CCPA) by embedding security into the data lifecycle. By establishing a 'Single Source of Truth,' we empower your organization to move from reactive reporting to predictive modeling and real-time operational intelligence.

                Data is often cited as the new oil, but without a modern refinery, it remains a liability rather than an asset. Our data modernization services focus on migrating legacy on-premise warehouses to high-performance cloud data platforms like Snowflake, BigQuery, or Databricks. We implement modern data stack (MDS) principles, including automated ELT pipelines, data modeling with dbt, and rigorous data quality monitoring. Beyond the architecture, we prioritize 'Data Democratization'—ensuring that business stakeholders have self-service access to reliable insights through governed BI layers. We also tackle the critical challenges of data privacy and compliance (GDPR/CCPA) by embedding security into the data lifecycle. By establishing a 'Single Source of Truth,' we empower your organization to move from reactive reporting to predictive modeling and real-time operational intelligence.`,
        image: "/images/data-modernization.webp"
    },
    'platform-modernization': {
        title: "Enterprise Platform Modernization",
        icon: Cloud,
        description: `Decouple from legacy constraints by migrating to cloud-native, microservices-based architectures. We help you increase deployment frequency and system resilience while drastically reducing operational overhead.`,
        content: `Legacy systems are often the biggest bottleneck to digital transformation. Our platform modernization approach isn't about a risky 'big bang' rewrite; it's about strategic, incremental evolution. We utilize the 'Strangler Fig' pattern to systematically replace monolithic components with scalable microservices and serverless functions. By adopting Containerization (Docker/Kubernetes) and Infrastructure as Code (Terraform), we enable your teams to deploy with confidence and speed. Our focus is on building 'Self-Healing' systems that offer 99.99% availability and can scale automatically during peak traffic. We also modernize your internal developer experience (DevEx), implementing CI/CD pipelines that reduce friction and allow your engineers to focus on building features rather than managing infrastructure. This shift results in a more agile, cost-effective, and future-proof enterprise core.

                Legacy systems are often the biggest bottleneck to digital transformation. Our platform modernization approach isn't about a risky 'big bang' rewrite; it's about strategic, incremental evolution. We utilize the 'Strangler Fig' pattern to systematically replace monolithic components with scalable microservices and serverless functions. By adopting Containerization (Docker/Kubernetes) and Infrastructure as Code (Terraform), we enable your teams to deploy with confidence and speed. Our focus is on building 'Self-Healing' systems that offer 99.99% availability and can scale automatically during peak traffic. We also modernize your internal developer experience (DevEx), implementing CI/CD pipelines that reduce friction and allow your engineers to focus on building features rather than managing infrastructure. This shift results in a more agile, cost-effective, and future-proof enterprise core.

                Legacy systems are often the biggest bottleneck to digital transformation. Our platform modernization approach isn't about a risky 'big bang' rewrite; it's about strategic, incremental evolution. We utilize the 'Strangler Fig' pattern to systematically replace monolithic components with scalable microservices and serverless functions. By adopting Containerization (Docker/Kubernetes) and Infrastructure as Code (Terraform), we enable your teams to deploy with confidence and speed. Our focus is on building 'Self-Healing' systems that offer 99.99% availability and can scale automatically during peak traffic. We also modernize your internal developer experience (DevEx), implementing CI/CD pipelines that reduce friction and allow your engineers to focus on building features rather than managing infrastructure. This shift results in a more agile, cost-effective, and future-proof enterprise core.`,
        image: "/images/platform-modernization.webp"
    },
    'application-management': {
        title: "Digital Application Management",
        icon: Layers,
        description: `Go beyond maintenance with proactive application evolution. We provide full-lifecycle management, performance optimization, and continuous feature enhancement to ensure your digital portfolio stays ahead.`,
        content: `The launch of an application is just the first day of its journey. To maintain value, digital applications require constant nurturing, optimization, and strategic updates. Our application management services provide a comprehensive framework for 'Continuous Evolution.' We take a proactive stance on application health, utilizing advanced observability tools to identify and resolve performance bottlenecks before they impact users. Our team handles everything from security patching and technical debt reduction to the rollout of new, high-impact features. We act as a strategic partner, regularly auditing your application portfolio to ensure alignment with shifting business goals. By balancing 'Keep the Lights On' (KTLO) activities with innovative enhancements, we maximize the total cost of ownership (TCO) and ensure your digital assets remain performant, secure, and competitive in a fast-moving market.

                The launch of an application is just the first day of its journey. To maintain value, digital applications require constant nurturing, optimization, and strategic updates. Our application management services provide a comprehensive framework for 'Continuous Evolution.' We take a proactive stance on application health, utilizing advanced observability tools to identify and resolve performance bottlenecks before they impact users. Our team handles everything from security patching and technical debt reduction to the rollout of new, high-impact features. We act as a strategic partner, regularly auditing your application portfolio to ensure alignment with shifting business goals. By balancing 'Keep the Lights On' (KTLO) activities with innovative enhancements, we maximize the total cost of ownership (TCO) and ensure your digital assets remain performant, secure, and competitive in a fast-moving market.

                The launch of an application is just the first day of its journey. To maintain value, digital applications require constant nurturing, optimization, and strategic updates. Our application management services provide a comprehensive framework for 'Continuous Evolution.' We take a proactive stance on application health, utilizing advanced observability tools to identify and resolve performance bottlenecks before they impact users. Our team handles everything from security patching and technical debt reduction to the rollout of new, high-impact features. We act as a strategic partner, regularly auditing your application portfolio to ensure alignment with shifting business goals. By balancing 'Keep the Lights On' (KTLO) activities with innovative enhancements, we maximize the total cost of ownership (TCO) and ensure your digital assets remain performant, secure, and competitive in a fast-moving market.`,
        image: "/images/application-management.webp"
    }
};
